# This docker-compose.yml is used for development. At is overwritten
# in part in production with `docker-compose.production.yml`
version: '2.3'

services:

  lab:
    build: .

  nsight:
    build:
      context: .
      dockerfile: Dockerfile.nsight

  nginx:
    # This port is for development only.
    ports:
      - $DEV_NGINX_PORT:80
